sudo: required
dist: trusty
language: node_js
services:
  - redis-server
before_install:
  - sudo apt-get install build-essential git cmake xsltproc  -y
#  - echo 'Installing firefox binaries'
#  - sudo apt-get install libpthread.so libdl.so libstdc++.so libm.so libgcc_s.so libc.so ld-linux-x86-64.so libXrender1.so libasound.so.2 libgtk-x11-2.0.so.0
#  - wget https://ftp.mozilla.org/pub/firefox/releases/49.0/linux-x86_64/en-US/firefox-49.0.tar.bz2
#  - sh -e /etc/init.d/xvfb start
  - npm install
env:
  - CXX=g++-4.8
#  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
cache:
  directories:
#  - node_modules
#  - typings
install:
  - npm run typings
  - npm run build
node_js:
  - "5.11"
notifications:
  email:
    recipients:
      - cooluhuru@gmail.com
    on_success: never
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)